repos:
    - original: https://golang.org/x/crypto
      repo: https://github.com/golang/crypto
      vcs: git
    - original: https://golang.org/x/net
      repo: https://github.com/golang/net
      vcs: git
    - original: https://golang.org/x/sync
      repo: https://github.com/golang/sync
      vcs: git
    - original: https://golang.org/x/sys
      repo: https://github.com/golang/sys
      vcs: git
    - original: https://golang.org/x/text
      repo: https://github.com/golang/text
      vcs: git
    - original: https://google.golang.org/genproto
      repo: https://github.com/google/go-genproto
      vcs: git
    - original: https://google.golang.org/grpc
      repo: https://github.com/grpc/grpc-go
      vcs: git

